### ISSUE TITLE
Líneas por traducir

### ISSUE THREAD

**Issue by deivids84** [ingbrzy/MA-XML-7.0-SPANISH#113]
Buenas!

He encontrado las siguientes lineas sin traducir. 

1. Galeria (líneas por traducir)
![screenshot_2016-04-02-02-36-23_com miui gallery](https://cloud.githubusercontent.com/assets/13929105/14224881/7b7143b0-f8ad-11e5-8489-0d2629679816.png)
![screenshot_2016-04-02-02-36-54_com miui gallery](https://cloud.githubusercontent.com/assets/13929105/14224882/7b71fa1c-f8ad-11e5-898c-382b1c62e4a8.png)
![screenshot_2016-04-02-02-39-06_com miui gallery](https://cloud.githubusercontent.com/assets/13929105/14224884/7b76216e-f8ad-11e5-868f-43f150218d52.png)
2. Fecha mal ordenada (Es un Mi Note), lo de la barra de búsqueda ya he visto que se actualiza sola al chino
![screenshot_2016-04-02-02-37-58_com miui home](https://cloud.githubusercontent.com/assets/13929105/14224883/7b7565a8-f8ad-11e5-8f33-6eb381753971.png)
3.Calendario
![screenshot_2016-04-02-02-41-55_com android calendar](https://cloud.githubusercontent.com/assets/13929105/14224886/7b89d2b8-f8ad-11e5-8e2b-6bfb68decd85.png)

Muchas gracias por vuestro trabajo.

**Comment by Infante007** [comment]
Hola estos temas los lleva @silver-james pero ya se pasara ,tiene mucho trabajo con otras rom y te dira lo que sea.
un saludo

**Comment by JS67** [comment]
Hola, yo he encontrado sin traducir:
- En las opciones de foto desde Galería: "Delete" y en "Mas": "Add to album" y "Details", aparte que el formato de la fecha está en inglés: "Abril 9" para "9 Abril"
- En "Contactos" sale "Add" en vez de "Añadir"
- En "Seguridad" - Permisos -. Install via USB
- En Configuracion adicional - Botones - "Automatically disable navigation buttons"
- En Calendario - Mas - Ajustes - "Notifications"
Si quereis, iré reportando las frases que queden sin traducir.
Muchas gracias,

**Comment by jamflux** [comment]
Hola @deivids84
Muchas cosas ya he solucionado que son problema de la traducción como por ejemplo:
-El asunto de las alarmas en días sábado y domingo
-Centro de seguridad traducido al 100
-Sugerencias y letras chinas en la barra de búsqueda del teléfono
Queda muy pendiente el asunto de la galería ya que no están en la galería en sí el problema.
Viene de la aplicación de la nube. Me pondré a ello cuando pueda.

Viendo que sólo queda ese pendiente cierro el caso. Sin embargo el recordatorio sigue en cuanto a la app de galería. Aún queda un caso que habla de ese temá, será cerrado en cuando se halle la solución.

To @ingbrzy 
May be you can add the lines to repos who has same  issue with chinese characthers, just see spanish strings for QuickSearchBox.apk because fix baidu and xiaomi search and sugerencies, were replaced with google search engine.
