### ISSUE TITLE
Error en app Actualizador

### ISSUE THREAD

**Issue by asirena** [ingbrzy/MA-XML-7.0-SPANISH#131]
La opción "Resumen de actualizaciones" lleva a un foro Czech&Slovak (ni siquiera inglés), a una página que además da error 404. ¿Sería posible que apuntara a 'http://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/' por ejemplo?

**Comment by jamflux** [comment]
Voy a decompilar toda la ROM y buscar, pero me late que este asunto obedece a un parche de xiaomi.eu y si es así no tendrá solución porque no sería tema de traducción. Indagaré.
Ya corregí algunas cosillas en ajustes.

**Comment by jamflux** [comment]
Cerrado el caso porque es un tema ajeno a la traducción, ya lo comprobé. Es un parche interno al cual no tengo acceso porque sólo ayudo en las traducciones no en la generación de ROMs.
May be @ingbrzy can help in this issue: in updater.apk when we go to "What´s new" tab we got a 404 error opening miuios.cz site, instead of xiaomi.eu reference like http://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/  
I know this is a patch but would be great if referal link was working.
Thank you @ingbrzy.
